sudo: false
language: python
python:
  - "3.3"
services:
  - redis-server
install:
  - make redis-install
  - pip install coverage python-coveralls tox
  - pip install -e .
script: 
  - make test
after_success: 
  - coveralls
